name: applauncher
description: "Android launcher app with TV remote support for auto-launching selected apps."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number for Android launcher app
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
version: 1.0.0+1

environment:
  sdk: ^3.9.2
  flutter: ">=3.16.0"

# Dependencies for Android launcher functionality
dependencies:
  flutter:
    sdk: flutter

  # Material icons for Android UI
  cupertino_icons: ^1.0.8
  
  # For getting installed apps
  installed_apps: ^1.6.0
  
  # For storing user preferences
  shared_preferences: ^2.2.2
  
  # For better TV list navigation
  scrollable_positioned_list: ^0.3.8

# Dev dependencies
dev_dependencies:
  flutter_launcher_icons: ^0.13.1

# Flutter launcher icons configuration
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "icon.png"

# Flutter configuration for Android launcher
flutter:
  uses-material-design: true
